### ISSUE TITLE
Mehr Admins fürs Repo

### ISSUE THREAD

**Issue by ChrisWint** [Tackyou/placebot-germany-target#5]
Hi,
angeblich läuft der Spaß nicht mehr lange und die Erweiterungen können nicht wirklich umgesetzt werden wenn die Bots dagegen ankämpfen. Daher bräuchten wir dringend mehr Leute mit zugriff aufs Repo. Wär top wenn du das noch `sehr bald™` bewerkstelligen könntest. Kannst mich nehmen oder im discord die Admins raussuchen oder so. @Tackyou @chinapwn @H3npi

**Comment by Erasio** [comment]
Erledigt :)
